### ISSUE TITLE
Need a better documentation - or at least, examples

### ISSUE THREAD

**Issue by jesuismaxime** [bnomei/kirby3-instagram#3]
There's no example for the "params in the config file" part and some settings (`debugforce`) differ from the usage example (`$force`).

Is there a precise order for the `expire` or `token` option in the function ?

**Comment by luxuryluke** [comment]
Yes, please.

**Comment by bnomei** [comment]
rejoice! i will do this today. :)

**Comment by bnomei** [comment]
@jesuismaxime  the order is set here:
https://github.com/bnomei/kirby3-instagram/blob/master/classes/Instagram.php#L48

anything you wanted to do with the function that is not possible yet?

**Comment by bnomei** [comment]
https://github.com/bnomei/kirby3-instagram/releases/tag/v1.1.0
